"""Adiciona coluna nome na tabela votos

Revision ID: 6396e5a91ee0
Revises: c8af2af68732
Create Date: 2025-07-04 10:16:29.619942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6396e5a91ee0'
down_revision = 'c8af2af68732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votos', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
